# Generated by Django 4.2 on 2023-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fullname',
            field=models.CharField(default=1, max_length=50, verbose_name='fullname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='img', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subjects',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
