# Generated by Django 4.2 on 2023-06-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_options_remove_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='blog.category'),
        ),
    ]
